### ISSUE TITLE
math.ceil raises ValueError for NaN and INF

### ISSUE THREAD

**Issue by jborbely** [MSLNZ/GTC#12]
In the `UncertainComplex._round` and `UncertainReal._round` methods the `math.ceil` function does not like NaN nor INF as an input value. 

Steps to reproduce the error:
```python
>>> a = ureal(nan, nan)
>>> a
ureal(nan,nan,inf)
>>> print(a)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Users\j.borbely\code\git\GTC\GTC\lib.py", line 398, in __str__
    gself = self._round(2,0)
  File "C:\Users\j.borbely\code\git\GTC\GTC\lib.py", line 297, in _round
    exponent = math.ceil( log10_u )
ValueError: cannot convert float NaN to integer
>>> a = ureal(inf, inf)
>>> a
ureal(inf,inf,inf)
>>> print(a)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Users\j.borbely\code\git\GTC\GTC\lib.py", line 398, in __str__
    gself = self._round(2,0)
  File "C:\Users\j.borbely\code\git\GTC\GTC\lib.py", line 297, in _round
    exponent = math.ceil( log10_u )
OverflowError: cannot convert float infinity to integer
```
This is the result in Python 3.6. I have not tested other Python versions.

**Comment by BlairDHall** [comment]
I have added tests to `ureal` and `ucomplex` that will catch inf and nan
arguments and raise a RuntimeError. `multiple_ureal` and
`multiple_ucomplex` call `ureal` and `ucomplex`respectively, so the user
will be prevented from making such assignments when defining uncertain
numbers.

I feel a little uneasy with this. It seems to be mollycoddling the
idiot-user somewhat, at the expense of overhead for everyone else to put up
with.

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by jborbely** [comment]
I was thinking about modifying the `UncertainReal._round` and `UncertainComplex._round` methods to handle the `exponent = math.ceil( log10_u )` issue directly. For example, suppose the following
```python
>>> a = ureal(1, 0.1)
>>> a
ureal(1.0,0.1,inf)
>>> print(a)
1.00(10)
```
Then `a` is used in a _complicated_ sequence of calculations and effectively something like this happens during the calculation
```python
>>> b = a/1e-320
>>> b
ureal(inf,inf,inf)
>>> print(b)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Users\j.borbely\code\git\GTC\GTC\lib.py", line 398, in __str__
    gself = self._round(2,0)
  File "C:\Users\j.borbely\code\git\GTC\GTC\lib.py", line 297, in _round
    exponent = math.ceil( log10_u )
OverflowError: cannot convert float infinity to integer
```
The user will still end up having this issue.

**Comment by BlairDHall** [comment]
Yes, I see. `_round` is still really a work in progress. It can be patched
up to display these odd values.

What do you think about restricting `inf` and `nan` during the definition
of uncertain numbers? There are checks on legal values for `u` and `df`, so
perhaps it is reasonable to extend that to include 'inf' for value and
uncertainty. I think `nan` is going a bit far, but since `nan` can be
produced in DoF calculations perhaps it should be checked for in the df
parameter.

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by jborbely** [comment]
I think that if somebody wanted to create an uncertain number using 'nan' and 'inf' for any of the input argument values (any of `x`, `u` or `df`) then we should let them. If `u` is not in [nan, inf] then make sure it is >=0. If `df` is not in [nan, inf] then make sure it is >=1.  Python 3 will propagate the 'inf' or 'nan' in a calculation and only seems to raise an exception when the value gets cast from a 'nan' or 'inf' to an `int`. Python 2 does seem to care at all.

Since we cannot control what happens during their calculation I think that we should just ensure that the `__str__` and `__repr__` calls won't raise an exception so that they can print their results even if something went terribly wrong in their calculation.

For example, we could add an extra `if` statement in both `_round` methods
```python
    def _round(self,digits,df_decimals):
        """ docstring... """
        if math.isnan(self.x) or math.isinf(self.x) or \
            math.isnan(self.u) or math.isinf(self.u):
            return GroomedUncertainReal(
                x = self.x,
                u = self.u,
                df = self.df,
                label = self.label,  # NOTE: the check for "if self.label is None", which is used below, is not necessary
                precision = digits,
                df_decimals = df_decimals,
                u_digits = '({})'.format(self.u)
            )
        elif self.u != 0:  # after here the code remains the same
            log10_u = math.log10( self.u )
            if log10_u.is_integer(): log10_u += 1 
            ...
```
Then if someone wanted to print any of these uncertain numbers they would get
```python
>>> a = [ureal(1.23, 0.456), ureal(1, inf, label='abc'), ureal(inf, 1, df=3), 
...      ureal(inf, inf, df=nan), ureal(1.23456, nan), ureal(nan, 1),
...      ureal(nan, nan, label='Hi'), ureal(nan, inf), ureal(inf, nan)]
>>> for u in a:
...     print('{0!s} {0!r}'.format(u))
...    
1.23(46) ureal(1.23,0.456,inf)
1.00(inf) ureal(1.0,inf,inf, label='abc')
inf(1.0) ureal(inf,1.0,3.0)
inf(inf) ureal(inf,inf,inf)  # the df=nan gets changed to inf in the __repr__ method because it fails the "if df < inf_dof" test (maybe this test should also be fixed to return nan if df=nan)
1.23(nan) ureal(1.23456,nan,inf)
nan(1.0) ureal(nan,1.0,inf)
nan(nan) ureal(nan,nan,inf, label='Hi')
nan(inf) ureal(nan,inf,inf)
inf(nan) ureal(inf,nan,inf)
```
In the future we could implement something more elegant that also fixes issue #1

**Comment by jborbely** [comment]
We should generate a list of all possible combinations (27 of them) of 'inf', 'nan' and 1.0 (i.e., any `numbers.Real` value) for `x`, `u` and `df` and make a unit test because the following will also still fail even with my suggestion above
```python
>>> print(ureal(1.23, 0.456, nan))
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "D:\code\git\GTC\GTC\lib.py", line 408, in __str__
    def real(self):
  File "D:\code\git\GTC\GTC\lib.py", line 339, in _round
    df_decimals = df_decimals,
ValueError: cannot convert float NaN to integer
```

**Comment by BlairDHall** [comment]
I have made the sort of change that you suggest to the two _round()
members, but I am not comfortable with allowing uncertain numbers to be
created with silly values. I have refined the checks I do in ureal() and
ucomplex() and now rely on math and cmath to raise exceptions in some
cases. I will commit this now.

I have done a little testing of this new behaviour of _round().

I am wondering what to do now about exceptions. There are a number of
RuntimeError exceptions that could be changed to ValueError or TypeError to
be a bit clearer. My dilemma is whether to use built-in classes or to
derive GTC exception classes and then use these for everything that get
raised in GTC. I am inclined to use the built-in classes, because, as I
said above, I am relying on some built-in exception behaviour. So, if I
were to create a clean exception hierarchy for GTC, I should really catch
these built-ins and re-raise them as GTC exceptions, which seems overly
pedantic.  Any thoughts?

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by jborbely** [comment]
I'm happy with raising an exception if someone calls `ureal` or `ucomplex` with silly values. It does make sense that we should guide the users to set up their calculation correctly.

I just pushed to _develop_ to also fix an additional test case that could occur in the `_round` methods. Please feel free to make further changes if you don't like the modifications that I made.

I think that we should use the built-in exception classes and use `ValueError`, `TypeError`, ... where appropriate.

**Comment by jborbely** [comment]
I'm happy with the changes made to the code to close this issue. Feel free to close it if you are also satisfied.
